physics:
  theta: 0.15
  mu: 0.0
  sigma: 0.2 
  dt: 0.1    

generation:
  batch_size: 1000
  total_time_steps: 1000

windowing:
  input_len: 100
  output_len: 50
  stride: 1

training:
  train_split: 0.8
  batch_size: 64

paths:
  next_token_data_path: "data/ou_next_token.pt"
  mean_pred_data_path: "data/ou_mean_pred.pt"
  multi_theta_data_path: "data/ou_multi_theta.pt"

multi_mean:
  num_trajectories: 10000
  mean_min: -1.5
  mean_max: 1.5

multi_theta:
  num_trajectories: 10000
  gamma: 5.0
  mean_min: -1.5
  mean_max: 1.5