hyperparameters:
  batch_size: 64
  learning_rate: 0.0003
  epochs: 3
  
system:
  device: "cpu"
  
paths:
  save_dir: "experiments"
  next_token_model_name: "model_next_token.pth"
  mean_pred_model_name: "model_mean_pred.pth"
  multi_theta_model_name: "model_multi_theta.pth"